### ISSUE TITLE
ecs Table 'mysql.plugin' doesn't exist

### ISSUE THREAD

**Issue by chengshea** [fungo/AliSQL-docker#1]
阿里 ecs 
```
alisql_alisql_1 | 2017-09-16T09:44:09.849897424Z 2017-09-16 09:44:09 1 [Note] mysqld: Shutdown complete
alisql_alisql_1 | 2017-09-16T09:44:09.849902221Z 
alisql_alisql_1 | 2017-09-16T09:45:10.682275722Z 2017-09-16 09:45:10 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
alisql_alisql_1 | 2017-09-16T09:45:10.682370426Z 2017-09-16 09:45:10 0 [Note] mysqld (mysqld 5.6.32) starting as process 1 ...
alisql_alisql_1 | 2017-09-16T09:45:10.685563819Z 2017-09-16 09:45:10 1 [Note] Plugin 'FEDERATED' is disabled.
alisql_alisql_1 | 2017-09-16T09:45:10.685997301Z mysqld: Table 'mysql.plugin' doesn't exist
alisql_alisql_1 | 2017-09-16T09:45:10.686009740Z 2017-09-16 09:45:10 1 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
alisql_alisql_1 | 2017-09-16T09:45:10.686276471Z Transparent huge pages are enabled, according to /sys/kernel/mm/transparent_hugepage/enabled
alisql_alisql_1 | 2017-09-16T09:45:10.686288497Z 2017-09-16 09:45:10 1 [ERROR] TokuDB: Huge pages are enabled, disable them before continuing
```
yml
```
alisql:
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=123221
  expose:
    - '3306:3306/tcp'
  memswap_limit: 0
  labels:
    aliyun.scale: '1'
  shm_size: 0
  image: 'alisql/alisql:latest'
  memswap_reservation: 0
  kernel_memory: 0
  mem_limit: 0
```
